### ISSUE TITLE
Panic-during-panic in `lightning-background-processor` tests

### ISSUE THREAD

**Issue by arik-so** [lightningdevkit/rust-lightning#2759]
https://github.com/lightningdevkit/rust-lightning/actions/runs/6950309022/job/18910198951?pr=2736

**Comment by TheBlueMatt** [comment]
Maybe

```
thread 'tests::test_background_event_handling' (8264) panicked at lightning-background-processor\src\lib.rs:3206:91:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/4a4ef493e3a1488c6e321570238084b38948f6db/library\std\src/panicking.rs:689:5
   1: core::panicking::panic_fmt
             at /rustc/4a4ef493e3a1488c6e321570238084b38948f6db/library\core\src/panicking.rs:80:14
   2: core::panicking::panic
             at /rustc/4a4ef493e3a1488c6e321570238084b38948f6db/library\core\src/panicking.rs:150:5
   3: core::option::unwrap_failed
             at /rustc/4a4ef493e3a1488c6e321570238084b38948f6db/library\core\src/option.rs:2199:5
   4: core::option::Option<T>::unwrap
             at /rustc/4a4ef493e3a1488c6e321570238084b38948f6db/library\core\src\option.rs:1016:21
   5: lightning_background_processor::tests::test_background_event_handling
             at .\src\lib.rs:3206:85
   6: lightning_background_processor::tests::test_background_event_handling::{{closure}}
             at .\src\lib.rs:3081:37
   7: core::ops::function::FnOnce::call_once
             at /rustc/4a4ef493e3a1488c6e321570238084b38948f6db/library\core\src\ops\function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
